import React from "react";
import { Button, Card, Col, Form, Row } from "react-bootstrap";
import { useMutation } from "@tanstack/react-query";
import { searchBookRent } from "../../API_Functions/APIs"; 
import { toast } from "react-toastify";

function SearchBook() {
  const [bookName, setBookName] = React.useState("");
  const [totalRent, setTotalRent] = React.useState(null);

  const searchBookRentMutation = useMutation({
    mutationKey: ["searchBookRent"],
    mutationFn: searchBookRent, 
    onSuccess: (data) => {
      setTotalRent(data.totalRent);
      toast.success("Book rent fetched successfully");
    },
    onError: (error) => {
      toast.error(error.message);
      console.log(error);
    },
  });

  const handleChange = (e) => {
    setBookName(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (bookName.trim() === "") {
      toast.error("Please enter a book name");
      return;
    }
    searchBookRentMutation.mutate({ bName: bookName });
  };

  return (
    <>
      <h1 className="text-center">Total Rent By Book</h1>
      <div className="d-flex justify-content-center">
        <Card style={{ padding: "20px", width: "50rem" }}>
          <Form onSubmit={handleSubmit}>
            <Row className="mb-3">
              <Form.Group as={Col} xs={9} controlId="formGridEmail">
                <Form.Control
                  type="text"
                  placeholder="Enter Book Name"
                  value={bookName}
                  onChange={handleChange}
                  required
                />
              </Form.Group>
              <Col xs={3}>
                <Button
                  variant="primary"
                  type="submit"
                  style={{ width: "100%" }}
                >
                  Search
                </Button>
              </Col>
            </Row>
          </Form>

          {totalRent !== null && (
            <Card.Footer as="h6">
              The total rent generated by this book is Rs. {totalRent}
            </Card.Footer>
          )}
        </Card>
      </div>
    </>
  );
}

export default SearchBook;
